language: python

matrix:
  include:
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
      dist: xenial
      sudo: true
    - os: osx
      language: generic

before_install: |	
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then	
    brew update
    brew upgrade python;
    python3.6 -m pip install -q virtualenv;
    virtualenv venv -p python3;
    source venv/bin/activate;
  fi

install:
  - pip3 install -r requirements.txt
  - python3 -m nltk.downloader vader_lexicon
  - python3 setup.py install
  - pip3 install nose

script:
  - nosetests
