language: python

matrix:
  include:
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
      dist: xenial
      sudo: true
    - os: osx
      language: generic

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi

install:
  - pip3 install -r requirements.txt
  - python3 -m nltk.downloader vader_lexicon
  - python3 setup.py install
  - pip3 install nose

script:
  - nosetests
